services:
  nginx:
    build: .
    container_name: nginx
    ports:
      - "80:80"

    volumes:
      - app_static_volume:/src/static/
      - app_media_volume:/src/media/
    networks:
      - nginx_network



volumes:
  app_static_volume:
  app_media_volume:


networks:
  nginx_network: