# Generated by Django 3.1.7 on 2021-04-15 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=110, verbose_name='نام')),
                ('last_name', models.CharField(max_length=120, verbose_name='تام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل شما ')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('09([0-9][0-9]|3[1-9]|2[1-9])-?[0-9]{3}-?[0-9]{4}', message='لطفا شناره تلفن صحیح وارد کنید شماره تلفن شما اشتباه است دوست من ')], verbose_name='شماره تماس ')),
                ('text', models.TextField(verbose_name='متن پیام ')),
            ],
        ),
    ]
