# Generated by Django 3.1.7 on 2021-04-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'پیام کاربر', 'verbose_name_plural': 'پیام های کاربران '},
        ),
    ]
