# Generated by Django 3.2.8 on 2021-10-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0003_alter_contactus_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='contactus',
            name='subject',
            field=models.CharField(default=1, max_length=500, verbose_name='عنوان '),
            preserve_default=False,
        ),
    ]
