# Generated by Django 3.2.8 on 2021-10-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0004_auto_20211020_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ'),
        ),
    ]
