# Generated by Django 3.2.8 on 2022-02-20 07:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0005_contactus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='متن پاسخ'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='پاسخ داده شده است ؟'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='is_observed',
            field=models.BooleanField(default=False, verbose_name='مشاهده شده است ؟'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=300, verbose_name='عنوان '),
        ),
    ]
