# Generated by Django 4.0.4 on 2022-05-03 20:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان نمونه کار')),
                ('company', models.CharField(max_length=120, verbose_name='شرکت')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات سابقه کار')),
                ('date', models.CharField(max_length=120, verbose_name='سال کار شما از سال ؟ تا سال؟')),
            ],
            options={
                'verbose_name': 'سابقه کار',
                'verbose_name_plural': 'سابقه کار ها ',
            },
        ),
    ]
