# Generated by Django 4.0.4 on 2022-05-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='WorkHistory',
        ),
    ]
