# Generated by Django 4.0.4 on 2022-05-03 21:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_rename_portfolio_workhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان تحصيلات')),
                ('field_of_study', models.CharField(max_length=120, verbose_name='رشته تحصيلي')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات تحصيلات')),
                ('date', models.CharField(max_length=120, verbose_name='سال کار شما از سال ؟ تا سال؟')),
            ],
            options={
                'verbose_name': 'سابقه تحصيل',
                'verbose_name_plural': 'سابقه تحصيلات ',
            },
        ),
    ]
