# Generated by Django 4.0.4 on 2022-05-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0006_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک وبسایت'),
        ),
    ]
