# Generated by Django 4.0.4 on 2022-05-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutme', '0002_aboutme_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان لینک ')),
                ('link', models.URLField(verbose_name='لینک ')),
                ('icon', models.CharField(choices=[('facebook', 'آیکون فیسبوک'), ('instagram', 'آیکون اینستاگرام'), ('twitter', 'آیکون توییتر'), ('telegram', 'آیکون تلگرام')], max_length=20, verbose_name='آیکون')),
            ],
            options={
                'verbose_name': 'لینک شبکه اجتماعی',
                'verbose_name_plural': 'لینک های شبکه های اجتماعی',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='aboutme',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='توضیحات تگ متا برای سئو'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='کلمات کلیدی تگ متا برای سئو'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='page_title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='عنوان ضفحه در مرورگر'),
        ),
    ]
