# Generated by Django 4.0.4 on 2022-05-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutme', '0003_socialmedia_aboutme_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.CharField(choices=[('facebook-f', 'آیکون فیسبوک'), ('instagram', 'آیکون اینستاگرام'), ('twitter', 'آیکون توییتر'), ('telegram', 'آیکون تلگرام')], max_length=20, verbose_name='آیکون'),
        ),
    ]
